
-- Exploratory Data Analysis --
-- creating database as name playstore_project

CREATE DATABASE PLAY_STORE;

USE PLAY_STORE;

SHOW TABLES;

CREATE TABLE PLAY_STORE_APPS(
    Id INT,
    App VARCHAR(255),
    Category VARCHAR(100),
    Rating DECIMAL(4,2),
    Reviews INT,
    Size VARCHAR(50),
    Installs INT,
    `Type` VARCHAR(10),
    Price DECIMAL(6,3),
    Content_Rating VARCHAR(100),
    Genres VARCHAR(255),
    Last_Updated DATE,
    Current_Ver VARCHAR(255),
    Android_Ver VARCHAR(255)
);

SELECT * FROM PLAY_STORE_APPS;

DESCRIBE TABLE PLAY_STORE_APPS;

CREATE OR REPLACE FILE FORMAT playstore_apps_csv_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE play_store_apps_stage
FILE_FORMAT = my_csv_format;

PUT file://C:/Users/Luffy/Desktop/playstore_reviews_analytics/data/cleaned/playstore_apps.csv @play_store_apps_stage;


COPY INTO PLAY_STORE_APPS
FROM @play_store_apps_stage/playstore_apps.csv
FILE_FORMAT = (FORMAT_NAME = playstore_apps_csv_format)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM PLAY_STORE_APPS;

SELECT * FROM PLAY_STORE_APPS LIMIT 10;

-- 1. Which apps have the highest rating in the given available dataset?

-- with window function and cte
WITH HGST_RATING AS(
    SELECT *, DENSE_RANK() OVER(ORDER BY RATING DESC) AS DR FROM PLAY_STORE_APPS
)
SELECT
APP, RATING
FROM HGST_RATING WHERE DR = 1;

-- There are total 270 apps with 5 star rating in provided play_store dataset

-- with sub-query
-- SELECT 
-- 	app, 
--     rating
-- FROM (  -- sub query 
-- 	SELECT 
-- 		*,
-- 		DENSE_RANK() OVER(ORDER BY rating DESC) AS rating_rank
-- 	FROM 
-- 		PLAY_STORE_APPS) AS test
-- WHERE 
-- 	rating_rank = 1;

-- 2. What are the number of installs and reviews for the above apps? 
-- Return the apps with the highest reviews to the top.

WITH HGST_RATING AS(
    SELECT *, DENSE_RANK() OVER(ORDER BY RATING DESC) AS DR FROM PLAY_STORE_APPS
)
SELECT APP, INSTALLS,RATING, REVIEWS FROM HGST_RATING WHERE DR = 1 ORDER BY REVIEWS DESC;

-- Ríos de Fe APP has 1000 installs and	5 star rating with 141 reviews

-- SELECT app,
--        Installs,
--        rating,
--        Reviews
--         -- sub query 
        
-- 	FROM (SELECT 
-- 		*,
-- 		DENSE_RANK() OVER(ORDER BY rating DESC) AS rating_rank
-- 	FROM 
-- 		PLAY_STORE_APPS) AS test
-- WHERE 
-- 	rating_rank = 1
--         order by 4 DESC;


-- 3. Which app has the highest number of reviews? Also, mention the number of reviews and category of the app.

SELECT APP, CATEGORY, REVIEWS FROM PLAY_STORE_APPS ORDER BY 3 DESC LIMIT 1;

-- Clash of Clans app falls under category of GAME with total of 44893888 reviews


/* 4. What is the total amount of revenue generated by the google play store by hosting apps? 
(Whenever a user buys apps from the google play store,
the amount is considered in the revenue) */


SELECT SUM(PRICE) AS TOTAL_AMNT_REV FROM PLAY_STORE_APPS WHERE UPPER(`TYPE`) = 'PAID';

-- total amount of revenue genarated by google playstore by hosting apps is 10408.85


/* 5. Which Category of google play store apps has the highest number of installs? 
also, find out the total number of installs for that particular category. */


SELECT CATEGORY, SUM(INSTALLS) AS SUM_INST FROM PLAY_STORE_APPS GROUP BY 1 ORDER BY SUM_INST DESC LIMIT 10;

-- Game category has highest number of installs with total installation of 29932164264


-- 6. Which Genre has the most number of published apps?


SELECT COUNT(APP) AS NUM_OF_APPS, GENRES FROM PLAY_STORE_APPS GROUP BY GENRES ORDER BY NUM_OF_APPS DESC LIMIT 1;

-- tools genre has the most number of published apps with count of 744


/* 7. Provide the list of all games ordered in such a way 
that the game that has the highest number of installs is displayed on the top
(to avoid duplicate results use distinct). */

SELECT DISTINCT(APP), INSTALLS FROM PLAY_STORE_APPS WHERE UPPER(CATEGORY) = 'GAME' ORDER BY 2 DESC;

-- subway surfers has highest number of installs in Game category


-- 8. Provide the list of apps that can work on android version 4.0.3 and UP.

SELECT APP FROM PLAY_STORE_APPS WHERE UPPER(ANDROID_VER) >= '4.0.3 AND UP';


-- 9. How many apps from the given data set are free? Also, provide the number of paid apps

SELECT `TYPE`, COUNT(*) FROM PLAY_STORE_APPS GROUP BY 1 LIMIT 2;

-- Paid = 700 and Free = 8434


-- 10. Which is the best dating app? (Best dating app is the one having the highest number of Reviews)

SELECT APP, CATEGORY, REVIEWS FROM PLAY_STORE_APPS
WHERE UPPER(CATEGORY) = 'DATING'
ORDER BY REVIEWS DESC
LIMIT 1;

-- Moco - chat, Meet People has highest number of reviews(313769) in Dating category


--  Creating table for playstore_reviews.csv

CREATE OR REPLACE TABLE PLAY_STORE_REVIEWS (
    id INT,
	App	TEXT,
    Translated_Review TEXT,
    Sentiment VARCHAR(25),
    Sentiment_Polarity DECIMAL(20,15),
    Sentiment_Subjectivity DECIMAL(20,15)
);

CREATE OR REPLACE FILE FORMAT playstore_rev_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE playstore_rev_stage
FILE_FORMAT = playstore_rev_format;

PUT file://C:/Users/Luffy/Desktop/playstore_reviews_analytics/data/cleaned/playstore_reviews.csv @playstore_rev_stage;

COPY INTO PLAY_STORE_REVIEWS
FROM @playstore_rev_stage/playstore_reviews.csv
FILE_FORMAT =(FORMAT_NAME = playstore_rev_format)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM PLAY_STORE_REVIEWS;

SELECT * FROM PLAY_STORE_REVIEWS LIMIT 10;


/* 11. Get the number of reviews having positive sentiment 
and number of reviews having negative sentiment for the app 10 best foods for you  
and compare them. */

SELECT
	SENTIMENT,
    COUNT(*) AS NUM_OF_SENTIMENTS
FROM
	PLAY_STORE_REVIEWS
WHERE 
	UPPER(APP) = '10 BEST FOODS FOR YOU' AND UPPER(SENTIMENT) IN ('POSITIVE', 'NEGATIVE')
GROUP BY 1;

-- There are 5 Negative sentiments and 79 Positive sentiments are present


/* 12. Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1? */

SELECT * FROM PLAY_STORE_REVIEWS
WHERE UPPER(APP) = 'ASUS SUPERNOTE' 
AND SENTIMENT_POLARITY = 1
AND SENTIMENT_SUBJECTIVITY = 1;


-- 13. Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat.

SELECT * FROM PLAY_STORE_REVIEWS
WHERE UPPER(APP) = 'ABS TRAINING-BURN BELLY FAT'
AND UPPER(SENTIMENT) = 'NEUTRAL';

-- There are total of 5 Abs Training-Burn belly fat apps with neutral sentiment present in provided dataset.


-- 14. Extract all negative sentiment reviews for Adobe Acrobat Reader 
-- with their sentiment polarity and sentiment subjectivity.

SELECT * FROM PLAY_STORE_REVIEWS
WHERE UPPER(APP) = 'ADOBE ACROBAT READER'
AND UPPER(SENTIMENT) = 'NEGATIVE';

-- There are total 20 Negative sentiment reviews present for app adobe acrobat reader.
